### ISSUE TITLE
Descripción del Articulo

### ISSUE THREAD

**Issue by LautaroMarchetti** [dariotroilo/TPINT_PROGAVANZ#2]
Autocompletar la descripción según el código cargado.

No permitir cargar registros de inventario con **descripcion** vacío.
![Registro sin Descripción](https://github.com/dariotroilo/TPINT_PROGAVANZ/assets/145359915/d9a0041a-fa1b-419e-bb6e-cb5b6a813d40)

**Comment by dariotroilo** [comment]
Que te parece?

![imagen](https://github.com/dariotroilo/TPINT_PROGAVANZ/assets/79846171/25ed6438-372b-440f-81d8-af1683285414)

**Comment by dariotroilo** [comment]
Resuelto, pero no esta mergeado el cambio aún.

**Comment by LautaroMarchetti** [comment]
Funciona ok. 
Muy buenas las alertas falta código o falta cantidad.
