### ISSUE TITLE
Error al querer ver siguiente pagina

### ISSUE THREAD

**Issue by LautaroMarchetti** [dariotroilo/TPINT_PROGAVANZ#6]
Cuando están completos los campos codigo y descripción, y se quiere visualizar los registros de la pagina 2 se genera el siguiente error.

Selección de pagina siguiente:
![Error al querer ver siguiente pagina](https://github.com/dariotroilo/TPINT_PROGAVANZ/assets/145359915/22a31453-6d8b-416c-bf0a-c8aebd9f6152)
Error generado:
![Error al querer ver siguiente pagina (2)](https://github.com/dariotroilo/TPINT_PROGAVANZ/assets/145359915/032fc5ca-f74f-49c2-89a0-1307b4586527)

**Comment by dariotroilo** [comment]
Este bug deriva del ingreso de campos en blanco.
Lo testeamos cuando arregle el otro.

**Comment by dariotroilo** [comment]
Lo labeleo como "Question" para que testeen

**Comment by LautaroMarchetti** [comment]
Quedó corregido el error.
